### ISSUE TITLE
Reduce tight coupling between gatsby-node.js and index.jsx.

### ISSUE THREAD

**Issue by haysclark** [haysclark/gatsby-starter-casper#13]
Per [conversation](https://github.com/infinitedescent/gatsby-pagination/issues/10) with @chmac, improve the current logic by reducing the data coupling between _gatsby-node.js_ and _index.jsx_.

The goal is reduce this [GraphQL query](https://github.com/haysclark/gatsby-starter-casper/blob/master/gatsby-node.js#L66-L83) down to an Array of _IDs_ or _slugs_.  Pass that Array of IDs to [_index.jsx_] and have the [GraphQL query](https://github.com/haysclark/gatsby-starter-casper/blob/master/src/templates/index.jsx#L126-L142) inside _index.jsx_ look up the needed posts by their ID.  

This is my starting point: [ StackOverflow on GraphQL example](https://stackoverflow.com/questions/40644296/how-to-query-list-of-objects-with-array-as-an-argument-in-graphql) which might be applied to Gatsby.

**Comment by haysclark** [comment]
After looking into this issue, it is not a trivial task and does not provide any significant advantage. This issue might be worth re-opening in the future once GraphQL _types_ are easier to implement in Gatsby.

**Comment by chmac** [comment]
Per my [last comment on our chat](https://github.com/infinitedescent/gatsby-pagination/issues/10), I think the solution is not to pass any IDs at all, but just pass `skip` and `limit` to each of the paginated pages.

In addition I'm passing 3 extra params which help with pagination, `totalPages` (which should probably be clearer as `totalPaginationPages`) and `prevPath` and `nextPath` which are either an empty string or a route to the previous / next pagination pages respectively.

This approach is remarkably simple. The `skip` and `limit` get passed to the query on the component, and that's all the component needs to get the correct set of edges. Then all my logic around fetching data, which data is required, etc, etc, is all handled in the component.
