### ISSUE TITLE
Fix "method_lines" issue in src/components/SEO/SEO.jsx

### ISSUE THREAD

**Issue by InfiniteEcco** [haysclark/gatsby-starter-casper#2]
Function `render` has 88 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/haysclark/gatsby-starter-casper/src/components/SEO/SEO.jsx#issue_5a4ececc84d0d60001000088

**Comment by haysclark** [comment]
Testing codeclimate integration.
