### ISSUE TITLE
Upgrade to v2

### ISSUE THREAD

**Issue by hnspn** [haysclark/gatsby-starter-casper#30]
Can we make a version of this starter that uses gatsby V2
I tried updating my own blog (made with this starter) to Gatsby V2 by following the official [migration guide](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#handling-breaking-changes) without any success

**Comment by haysclark** [comment]
Upgraded to Gatsby v2 in https://github.com/haysclark/gatsby-starter-casper/commit/bbab4d46a3918747b1566dc752a7be436ec0fabf
