### ISSUE TITLE
syntax highlighting does not work by default

### ISSUE THREAD

**Issue by hnspn** [haysclark/gatsby-starter-casper#32]
The syntax highlighting for code in markdown files is not working.

This is the default 'Big text' blog post where syntax highling is showcased.

<img width="802" alt="screen shot 2018-10-09 at 6 27 39 pm" src="https://user-images.githubusercontent.com/22123928/46702429-0cf8f800-cbf1-11e8-8343-4d24c2284dcc.png">

As you can see, no colors

This is an easy fix.
You just need to import the prism css file in the index.jsx file
`import 'prismjs/themes/prism.css'`

I'll make a PR

**Comment by haysclark** [comment]
Code merged.
