### ISSUE TITLE
post cover  how to modify to be able use in cover image from static folder

### ISSUE THREAD

**Issue by netmoleCZ** [haysclark/gatsby-starter-casper#5]
good day  can anybody suggest me how to use as cover image from static folder

**Comment by haysclark** [comment]
@netmoleCZ I actually have been fighting with this issue myself.  I've only been able to use relative urls in my .md file.

```
---
title: "new site"
description: "some website!"
cover: "./website-image.png"
author: "mr. t"
date: "2018-01-09T21:54:06.888Z"
category: "Foo"
slug: "woot"
tags:
-   blog
---

... your .md blog post...
```

_website-image.png_ then needs to be located inside of the _content_ folder with that blog post, not the _static_ folder.  It will be moved by Gatsby at build time.  Make sure to look up 'gatsby-transformer-remark' and 'gatsby-remark-images' to learn more.
